### ISSUE TITLE
Gem release

### ISSUE THREAD

**Issue by atz** [sul-dlss/mods#17]
I bumped the version number to cover my recent changes.  Please cut a gem release and git tag.  To be consumed by standford-mods.

(If you want to educate me on how to do our gem releases, I'm willing to learn.)

**Comment by atz** [comment]
@cbeer @ndushay

**Comment by ndushay** [comment]
@atz I think it's as simple as:
1. get the stuff you want in the master branch, including the bumped version number.
2. make sure the tests pass
3. rake release
I will doublecheck gem ownership - what is your rubygems sign on?

**Comment by cbeer** [comment]
@atz get yourself on https://consul.stanford.edu/display/DSG/Roster+and+Phone+List+for+DLSS+Staff and you'll get access to all the gems within 24 hours.

**Comment by ndushay** [comment]
ALL TEH GEMS!!!!!!!!

**Comment by atz** [comment]
Just registered `atz`

**Comment by atz** [comment]
Added self to consul.

**Comment by jcoyne** [comment]
@atz I think this can be closed?

**Comment by atz** [comment]
Yep
