### ISSUE TITLE
Support MODS 3.6

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/mods#24]
Story level ticket to start with for analysis. Changes are described at https://www.loc.gov/standards/mods/changes-3-6.html

Metadata dept is interested in using the new \<nameIdentifier> field

Implications
- update schema declarations
- update xslt for MARC inport
- update MODS display rules and Stanford MODS gem
- add new fields to Modsulator

**Comment by arcadiafalcone** [comment]
Also: update modsulator

**Comment by LynnMcRae** [comment]
Determine if there's a MARC to MODS 3.6 xslt and if it accommodates the new MARC $1 for nameIdentifier

**Comment by arcadiafalcone** [comment]
Yes, there is a 3.6 XSLT. However, it maps the $0 to nameIdentifier, as $1 has not yet been implemented in MARC. In practice thus far $0 has been used for both authority URIs and RWO URIs. In the 3.5 XSLT, $0 is mapped to the xlink attribute.

If it's feasible to support nameIdentifier on the MODS side, and then update the MARC XSLT once LC has formalized the $1, that would meet the immediate use case of researcher identifiers like ORCID for datasets, which are unlikely to have MARC records.

Subfield $1 proposal (released 1/4/2017): https://www.loc.gov/marc/mac/2017/2017-dp01.html

Stylesheets
XSLT 1.0: http://www.loc.gov/standards/mods/v3/MARC21slim2MODS3-6.xsl
XSLT 2.0: http://www.loc.gov/standards/mods/v3/MARC21slim_MODS3-6_XSLT2-0.xsl

**Comment by LynnMcRae** [comment]
I assume there is an immediate value for DOR to upgrade to 3.6 in the ability to start capturing the nameIdentifier, say, via Modsulator, for DOR managed MODS. Is there a similar urgency in upgrading the MARC-to-MODS now? or rather, assuming we WOULD do the XSLT upgrade at the same time, is it ok if $0 is what's mapped and perhaps LoC will update the XSLT once the MARC update is introduced? That is, is there an advantage to customizing the XSLT in the short term to bring in $1 asap? For instance, is SUL already starting to use $1 locally? Let me know if the quesiton doesn't make sense.

**Comment by arcadiafalcone** [comment]
I don't think there's an urgency in updating the MARC-to-MODS, as implementing the $1 locally hasn't even been discussed yet, and as it's not yet official I don't expect it to be in any records coming from other sources. I would prefer to retain the old mapping for the time being so that we can keep the data in <nameIdentifier> cleaner, since the $0 also includes data that should map to authorityURI. That way we can make sure <nameIdentifier> contains only RWO URIs.

**Comment by LynnMcRae** [comment]
Superceded by new story ticket https://github.com/sul-dlss/infrastructure-stories/issues/1
